apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-feeds-api
  name: udagram-feeds-api-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-feeds-api
